# docker-compose up -d
# docker build -t <container_name> .
# docker run -it <container_name> sh

version: '3'
services:
  hamster_mayhem_telegram-bot:
    build: .
    container_name: Hamster_Mayhem_tg-bot
    volumes:
      - ./bot:/app/bot
    restart: unless-stopped
